/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hmjuernoxqkawnezcved"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtanVlcm5veHFrYXduZXpjdmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMzE1MjMsImV4cCI6MjA3ODYwNzUyM30.4QDPqEILBD4m-5Hv1B-3QRd8NV630-l5YQ1-oTWdjTY"